H2-AOAO/Server

- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> [FEATURE] 이슈, PR 템플릿 수정

- src/main/java/kr/sesac/aoao/server/dino/controller/DinoController.java
- src/main/java/kr/sesac/aoao/server/dino/controller/dto/GetUserDinoResponse.java
- src/main/java/kr/sesac/aoao/server/dino/domain/Dino.java
- src/main/java/kr/sesac/aoao/server/dino/exception/DinoErrorCode.java
- src/main/java/kr/sesac/aoao/server/dino/repository/DinoEntity.java
- src/main/java/kr/sesac/aoao/server/dino/repository/DinoInfoEntity.java
- src/main/java/kr/sesac/aoao/server/dino/repository/DinoJpaRepository.java
- src/main/java/kr/sesac/aoao/server/dino/service/DinoService.java
- src/main/java/kr/sesac/aoao/server/dino/service/DinoServiceImpl.java
- src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
- src/test/java/kr/sesac/aoao/server/dino/service/DinoServiceImplTest.java
- 내 공룡 페이지 가져오기
- 공룡 테이블 엔티티 생성
resolve #15
> [FEATURE] 공룡 테이블 조회 API 

- src/main/java/kr/sesac/aoao/server/dino/controller/DinoController.java
- src/main/java/kr/sesac/aoao/server/dino/repository/DinoJpaRepository.java
- src/main/java/kr/sesac/aoao/server/dino/service/DinoServiceImpl.java
- src/main/java/kr/sesac/aoao/server/item/controller/ItemController.java
- src/main/java/kr/sesac/aoao/server/item/controller/dto/GetItemInfoResponse.java
- src/main/java/kr/sesac/aoao/server/item/controller/dto/UseItemNumResponse.java
- src/main/java/kr/sesac/aoao/server/item/domain/Item.java
- src/main/java/kr/sesac/aoao/server/item/exception/ItemErrorCode.java
- src/main/java/kr/sesac/aoao/server/item/repository/ItemEntity.java
- src/main/java/kr/sesac/aoao/server/item/repository/ItemJpaRepository.java
- src/main/java/kr/sesac/aoao/server/item/repository/UserItemEntity.java
- src/main/java/kr/sesac/aoao/server/item/repository/UserItemJpaRepository.java
- src/main/java/kr/sesac/aoao/server/item/service/ItemService.java
- src/main/java/kr/sesac/aoao/server/item/service/ItemServiceImpl.java
- src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
- 아이템 정보 테이블 작성
- 유저 아이템 테이블 작성
- 유저 - 유저 아이템 - 아이템 정보 테이블 매핑
- 아이템 구매 / 삭제 개수 조절 API 작성
resolve #21
> [FEAT] 아이템 테이블 추가 & 개수 조절 API

- src/main/java/kr/sesac/aoao/server/dino/controller/DinoController.java
- src/main/java/kr/sesac/aoao/server/dino/repository/DinoJpaRepository.java
- src/main/java/kr/sesac/aoao/server/dino/service/DinoServiceImpl.java
- src/main/java/kr/sesac/aoao/server/global/entity/BaseEntity.java
- src/main/java/kr/sesac/aoao/server/item/controller/dto/UseItemNumResponse.java
- src/main/java/kr/sesac/aoao/server/todo/config/InitializingPaletteConfig.java
- src/main/java/kr/sesac/aoao/server/todo/controller/TodoFolderController.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/request/TodoFolderSaveRequest.java
- src/main/java/kr/sesac/aoao/server/todo/domain/Palette.java
- src/main/java/kr/sesac/aoao/server/todo/exception/PaletteErrorCode.java
- src/main/java/kr/sesac/aoao/server/todo/exception/TodoErrorCode.java
- src/main/java/kr/sesac/aoao/server/todo/repository/PaletteEntity.java
- src/main/java/kr/sesac/aoao/server/todo/repository/PaletteJpaRepository.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderEntity.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderJpaRepository.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderService.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderServiceImpl.java
- src/main/java/kr/sesac/aoao/server/user/exception/UserErrorCode.java
- src/main/resources/application.yml
- src/test/java/kr/sesac/aoao/server/dino/service/DinoServiceImplTest.java
- src/test/java/kr/sesac/aoao/server/todo/service/TodoFolderServiceImplTest.java
- src/test/java/kr/sesac/aoao/server/user/controller/UserControllerTest.java
- 투두리스트 폴더 생성 API 구현
- 어플리케이션 실행 시 팔레트 정보 저장
resolve #14
> [FEATURE] 투두리스트 폴더 생성 API 구현

- src/main/java/kr/sesac/aoao/server/todo/controller/TodoFolderController.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/request/TodoFolderUpdateRequest.java
- src/main/java/kr/sesac/aoao/server/todo/exception/TodoFolderErrorCode.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderEntity.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderService.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderServiceImpl.java
- src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
- 투두리스트 폴더 수정 API 구현
- 투두리스트 폴더 삭제 API 구현
resolve #28
> [FEATURE] 투두리스트 폴더 수정 및 삭제 API 구현

- src/main/java/kr/sesac/aoao/server/global/config/SecurityConfig.java
- src/main/java/kr/sesac/aoao/server/todo/controller/TodoController.java
- src/main/java/kr/sesac/aoao/server/todo/controller/TodoFolderController.java
- src/main/java/kr/sesac/aoao/server/todo/controller/TodoQueryController.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/request/TodoSaveRequest.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/request/TodoUpdateRequest.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/FolderDetailResponse.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/FolderQueryDetailResponse.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/PaletteDetailResponse.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/PaletteQueryDetailResponse.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/TodoDetailResponse.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/TodoFolderDetailResponse.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/TodoQueryDetailResponse.java
- src/main/java/kr/sesac/aoao/server/todo/exception/TodoErrorCode.java
- src/main/java/kr/sesac/aoao/server/todo/repository/PaletteEntity.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoEntity.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderEntity.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderJpaRepository.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoJpaRepository.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderService.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderServiceImpl.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoQueryService.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoQueryServiceImpl.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoService.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoServiceImpl.java
- src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
- 투두리스트 폴더 목록 조회
- 투두리스트 폴더 색상 목록 조회
- 투두 항목 작성
- 투두 항목 수정
- 투두 항목 삭제
- 투두 항목 체크
- 투두 항목 체크 취소
- 투두리스트 조회
resolve #31
> [FEATURE] 투두 항목 API 구현

- src/main/java/kr/sesac/aoao/server/point/repository/PointEntity.java
- src/main/java/kr/sesac/aoao/server/point/repository/PointJpaRepository.java
- src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
> [FEATURE] 포인트 엔티티 생성

- settings.gradle
- src/main/java/kr/sesac/aoao/server/diary/controller/DiaryController.java
- src/main/java/kr/sesac/aoao/server/diary/controller/dto/request/DiaryCreateRequest.java
- src/main/java/kr/sesac/aoao/server/diary/controller/dto/request/DiaryUpdateRequest.java
- src/main/java/kr/sesac/aoao/server/diary/controller/dto/response/GetDiaryDetailResponse.java
- src/main/java/kr/sesac/aoao/server/diary/controller/dto/response/GetDiaryResponse.java
- src/main/java/kr/sesac/aoao/server/diary/domain/Diary.java
- src/main/java/kr/sesac/aoao/server/diary/exception/DiaryErrorCode.java
- src/main/java/kr/sesac/aoao/server/diary/repository/DiaryEntity.java
- src/main/java/kr/sesac/aoao/server/diary/repository/DiaryJpaRepository.java
- src/main/java/kr/sesac/aoao/server/diary/service/DiaryService.java
- src/main/java/kr/sesac/aoao/server/diary/service/DiaryServiceImpl.java
- src/test/java/kr/sesac/aoao/server/diary/service/DiaryServiceImplTest.java
- 다이어리 조회
- 다이어리 작성
- 다이어리 수정
- 다이어리 삭제
resolve #35
> [FEAT] 다이어리 조회, 작성, 수정, 삭제 API 구현 초안

- settings.gradle
- rootProject 명 변경
resolve #45
> [BUG] rootProject 명 변경

- src/main/java/kr/sesac/aoao/server/todo/controller/TodoController.java
- src/main/java/kr/sesac/aoao/server/todo/controller/TodoFolderController.java
- 응답값이 없는 API 에 응답값 추가
resolve #49
> [BUG] 응답값이 없는 API 에 응답값 추가

- src/main/java/kr/sesac/aoao/server/user/controller/UserController.java
- 회원가입 관련 HTTP Method 변경
resolve #61
> [BUG] 회원가입 관련 HTTP Method 변경

- src/main/java/kr/sesac/aoao/server/point/repository/PointEntity.java
- src/main/java/kr/sesac/aoao/server/todo/exception/TodoFolderErrorCode.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoEntity.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderEntity.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderServiceImpl.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoServiceImpl.java
- src/main/java/kr/sesac/aoao/server/user/controller/UserController.java
- src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
> [FEATURE] 투두 관련 포인트 부여

- .gitignore
- build.gradle
- scripts/deploy.sh
- src/main/java/kr/sesac/aoao/server/diary/repository/DiaryEntity.java
- src/main/java/kr/sesac/aoao/server/diary/repository/DiaryJpaRepository.java
- src/main/java/kr/sesac/aoao/server/diary/service/DiaryServiceImpl.java
- src/main/java/kr/sesac/aoao/server/dino/repository/DinoEntity.java
- src/main/java/kr/sesac/aoao/server/dino/repository/DinoInfoEntity.java
- src/main/java/kr/sesac/aoao/server/dino/repository/DinoInfoJpaRepository.java
- src/main/java/kr/sesac/aoao/server/dino/service/DinoServiceImpl.java
- src/main/java/kr/sesac/aoao/server/global/config/SecurityConfig.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderEntity.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderJpaRepository.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoQueryServiceImpl.java
- src/main/resources/application-dev.yml
- src/main/resources/application-local-db.yml
- src/main/resources/application-local.yml
- 운영 환경 별 application.yml 분리
- AWS RDS connection 확인
- entity 에 있는 oracle 예약어 수정
resolve #65
> [FEATURE] dev 환경 배포

- scripts/deploy.sh
- src/main/java/kr/sesac/aoao/server/dino/service/DinoServiceImpl.java
- 다이노 레벨 수정 및 배포 스크립트 수정
resolve #69
> [BUG] 다이노 레벨 수정 및 배포 스크립트 수정

- scripts/deploy.sh
- src/main/java/kr/sesac/aoao/server/user/service/UserServiceImpl.java
> [CHORE] 유저 아이템 생성 코드 수정

- src/main/java/kr/sesac/aoao/server/item/repository/ItemJpaRepository.java
- src/main/java/kr/sesac/aoao/server/item/repository/UserItemEntity.java
- src/main/java/kr/sesac/aoao/server/item/repository/UserItemJpaRepository.java
- src/main/java/kr/sesac/aoao/server/user/service/UserServiceImpl.java
> [BUG] 유저 아이템 추가

- src/main/java/kr/sesac/aoao/server/todo/domain/Palette.java
> [FEATURE] 투두리스트 폴더 색상 추가

- src/main/java/kr/sesac/aoao/server/diary/controller/dto/response/GetDiaryResponse.java
- src/main/java/kr/sesac/aoao/server/diary/exception/DiaryErrorCode.java
- src/main/java/kr/sesac/aoao/server/diary/repository/DiaryEntity.java
- src/main/java/kr/sesac/aoao/server/diary/repository/DiaryJpaRepository.java
- src/main/java/kr/sesac/aoao/server/diary/service/DiaryServiceImpl.java
- 다이어리 엔티티의 날짜 타입은 LocalDateTime
- API 에서 date 정보를 받아와 repository 메서드를 호출하는 값은 2024-01-26
- 실제 DB 에 저장된 값은 시간 값이 포함되어 조회되지 않았음
resolve #80
> [BUG] 다이어리 API 수정

- src/main/java/kr/sesac/aoao/server/todo/config/InitializingPaletteConfig.java
- 팔레트가 계속해서 저장되는 문제 해결
resolve #82
> [BUG] 팔레트가 계속해서 저장되는 문제 해결

- src/main/java/kr/sesac/aoao/server/dino/service/DinoServiceImpl.java
- src/main/java/kr/sesac/aoao/server/todo/controller/TodoController.java
- src/main/java/kr/sesac/aoao/server/todo/controller/TodoFolderController.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/FolderDetailResponse.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/FolderSaveResponse.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/TodoFolderDetailResponse.java
- src/main/java/kr/sesac/aoao/server/todo/controller/dto/response/TodoSaveResponse.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderJpaRepository.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoService.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoServiceImpl.java
- src/main/java/kr/sesac/aoao/server/user/controller/dto/response/MyPageResponse.java
- src/main/java/kr/sesac/aoao/server/user/service/UserServiceImpl.java
- 투두 항목 생성 시 투두 아이디 추가
- 투두리스트 조회 API 요청 시 팔레트 아이디 추가
- 폴더 생성 시 폴더 아이디 추가
- 폴더 리스트 조회 API 요청 시 팔레트 아이디 추가
- 다이노 리스트 조회 시 생성 시간 기준으로 정렬
- 마이페이지 조회 시 today 순서 바꾸기
- 마이페이지에 본인 여부 추가
resolve #84
> [BUG] 전반적인 API 개선

- .github/workflows/gradle.yml
> [FEAT] Create gradle.yml

- .github/workflows/gradle.yml
> [FEAT] ci/cd 구축

- src/main/java/kr/sesac/aoao/server/todo/domain/Palette.java
- src/main/java/kr/sesac/aoao/server/todo/exception/PaletteErrorCode.java
- src/main/java/kr/sesac/aoao/server/todo/exception/TodoErrorCode.java
- src/main/java/kr/sesac/aoao/server/todo/exception/TodoFolderErrorCode.java
- src/main/java/kr/sesac/aoao/server/todo/repository/PaletteEntity.java
- src/main/java/kr/sesac/aoao/server/todo/repository/PaletteJpaRepository.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoEntity.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderEntity.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoFolderJpaRepository.java
- src/main/java/kr/sesac/aoao/server/todo/repository/TodoJpaRepository.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoFolderService.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoQueryService.java
- src/main/java/kr/sesac/aoao/server/todo/service/TodoService.java
- 투두리스트 및 폴더 관련 주석 추가
resolve #92
> [FEATURE] 투두리스트 및 폴더 관련 주석 추가

- src/main/java/kr/sesac/aoao/server/user/domain/User.java
- src/main/java/kr/sesac/aoao/server/user/exception/UserErrorCode.java
- src/main/java/kr/sesac/aoao/server/user/jwt/JwtAuthenticationFilter.java
- src/main/java/kr/sesac/aoao/server/user/jwt/JwtTokenProvider.java
- src/main/java/kr/sesac/aoao/server/user/jwt/Subject.java
- src/main/java/kr/sesac/aoao/server/user/repository/RefreshTokenEntity.java
- src/main/java/kr/sesac/aoao/server/user/repository/TokenJpaRepository.java
- src/main/java/kr/sesac/aoao/server/user/repository/UserEntity.java
- src/main/java/kr/sesac/aoao/server/user/repository/UserJpaRepository.java
- src/main/java/kr/sesac/aoao/server/user/repository/UserType.java
- src/main/java/kr/sesac/aoao/server/user/service/KaKaoLoginService.java
- src/main/java/kr/sesac/aoao/server/user/service/UserService.java
- src/main/java/kr/sesac/aoao/server/user/service/UserServiceImpl.java
> [FEAT] 유저 부분 주석 추가
